# Generated by Django 2.0.7 on 2018-07-13 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180713_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('primary_phone', models.CharField(max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('lived_in_usa', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('national_id_type', models.IntegerField(choices=[(0, 'Cedula'), (1, 'Passport'), (2, 'Social Security Number')], default=0)),
                ('national_id_number', models.CharField(max_length=15)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Rather not say')], default=0)),
                ('address_line_one', models.CharField(max_length=150)),
                ('address_line_two', models.CharField(blank=True, max_length=150)),
                ('active_studies', models.BooleanField(default=False)),
                ('career', models.CharField(blank=True, max_length=50)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('currently_employed', models.BooleanField(default=False)),
                ('current_employer', models.CharField(blank=True, max_length=50)),
                ('previous_call_center_xp', models.BooleanField(default=False)),
                ('pre_screen', models.BooleanField(default=False)),
                ('hire_iq', models.IntegerField(blank=True, null=True)),
                ('tss', models.BooleanField(default=False)),
                ('hm_interview', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'permissions': (('change_status', 'can change status'), ('view_status', 'can view status')),
            },
        ),
        migrations.CreateModel(
            name='AreaOfExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_form', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'area of experience',
                'verbose_name_plural': 'areas of experience',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_form', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'call center',
                'verbose_name_plural': 'call centers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_form', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityTown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_form', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'city or town',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_form', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_form', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_in_form', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='career',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to='applications.Institution'),
        ),
        migrations.AddField(
            model_name='application',
            name='areas_of_expertise',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='applications.AreaOfExpertise'),
        ),
        migrations.AddField(
            model_name='application',
            name='city_or_town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.CityTown'),
        ),
        migrations.AddField(
            model_name='application',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='applications.Language'),
        ),
        migrations.AddField(
            model_name='application',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.Person'),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_call_center',
            field=models.ManyToManyField(blank=True, related_name='applications', to='applications.CallCenter'),
        ),
    ]
