# Generated by Django 2.0.7 on 2018-07-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('primary_phone', models.CharField(max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('lived_in_usa', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('national_id_type', models.IntegerField(choices=[(0, 'Cedula'), (1, 'Passport'), (2, 'Social Security Number')], default=0)),
                ('national_id_number', models.CharField(max_length=15)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Rather not say')], default=0)),
                ('address_line_one', models.CharField(max_length=150)),
                ('address_line_two', models.CharField(blank=True, max_length=150)),
                ('active_studies', models.BooleanField(default=False)),
                ('career', models.CharField(blank=True, max_length=50)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('pre_screen', models.BooleanField(default=False)),
                ('hire_iq', models.IntegerField(blank=True, null=True)),
                ('tss', models.BooleanField(default=False)),
                ('hm_interview', models.BooleanField(default=False)),
                ('national_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.NationalId')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.Person')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'permissions': (('change_status', 'can change status'), ('view_status', 'can view status')),
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50, unique=True)),
                ('trade_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=15, unique=True)),
                ('long_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to='applications.Institution'),
        ),
    ]
